global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Numerics;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Serialization;
global using QuadToSpine2D.Core.Data;
global using QuadToSpine2D.Core.Data.Quad;