using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ServiceSourceGenerators;

/// <summary>
/// 源代码生成器，用于自动扫描标记了 [Service] 特性的类，
/// 并在 Instances.AddServices() 方法中生成相应的服务注册代码
/// </summary>
[Generator]
public class SourceGeneratorWithAttributes : IIncrementalGenerator
{
    private const string TargetNamespace = "QTSAvalonia.Helper";
    private const string AttributeName = "ServiceAttribute";
    

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册语法提供程序来查找标记了 [Service] 特性的类
        var provider = context.SyntaxProvider
                              .CreateSyntaxProvider(
                                  predicate: static (s,   _) => IsSyntaxTargetForGeneration(s),
                                  transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                              .Where(static m => m is not null)
                              .Select((t, _) => t!);

        // 注册源代码输出
        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(provider.Collect()),
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    /// <summary>
    /// 判断语法节点是否是目标（标记了特性的类声明）
    /// </summary>
    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    /// <summary>
    /// 获取语义目标（带 [Service] 特性的类信息）
    /// </summary>
    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;

        // 遍历类的所有特性
        foreach (var attributeListSyntax in classDeclarationSyntax.AttributeLists)
        {
            foreach (var attributeSyntax in attributeListSyntax.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                    continue;

                var attributeName = attributeSymbol.ContainingType.ToDisplayString();

                // 检查是否是 [Service] 特性
                if (attributeName == $"{TargetNamespace}.{AttributeName}" || 
                    attributeName == AttributeName ||
                    attributeSymbol.ContainingType.Name == AttributeName)
                {
                    return classDeclarationSyntax;
                }
            }
        }

        return null;
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> serviceClasses,
        SourceProductionContext context)
    {
        if (serviceClasses.IsDefaultOrEmpty)
            return;

        // 收集所有服务类信息
        var serviceInfos = new List<ServiceClassInfo>();
        
        foreach (var classDeclaration in serviceClasses)
        {
            var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is INamedTypeSymbol classSymbol)
            {
                serviceInfos.Add(new ServiceClassInfo(
                    classSymbol.Name,
                    classSymbol.ContainingNamespace.ToDisplayString(),
                    classSymbol.ToDisplayString()));
            }
        }

        // 生成 Instances 类的部分类实现
        var source = GenerateInstancesPartialClass(serviceInfos);
        context.AddSource("Instances.ServiceRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// 生成 Instances 类的部分类实现
    /// </summary>
    private static string GenerateInstancesPartialClass(List<ServiceClassInfo> serviceClasses)
    {
        var serviceRegistrations = serviceClasses
            .Select(info => $"services.AddSingleton<{info.FullName}>();")
            .ToArray();

        return $$"""
                 // <auto-generated/>

                 using Microsoft.Extensions.DependencyInjection;

                 namespace QTSAvalonia.Helper
                 {
                     public static partial class Instances
                     {
                         static partial void AddServices(IServiceCollection services)
                         {
                 {{string.Join("\n", serviceRegistrations.Select(s => "             " + s))}}
                         }
                     }
                 }
                 """;
    }
    
    /// <summary>
    /// 服务类信息
    /// </summary>
    private class ServiceClassInfo(string name, string ns, string fullName)
    {
        public string Name      { get; } = name;
        public string Namespace { get; } = ns;
        public string FullName  { get; } = fullName;
    }
}